### ISSUE TITLE
Add profile information to the user object

### ISSUE THREAD

**Issue by jamiedavenport** [jamiedavenport/nauth0#23]
- Name
- Email
- Profile picture

The changes will need to be applied to this method: https://github.com/jamiedavenport/nauth0/blob/8f06d623b018e073e4e9a8a117a1e25b1310a4d9/packages/nauth0/src/server/session.ts#L10

**Comment by fakoredeDamilola** [comment]
I want to try my hands on this

**Comment by jamiedavenport** [comment]
@fakoredeDamilola be my guest. Unfortunately, there are no contributing guidelines just yet but I'll put something together soon. I appreciate the help.

**Comment by jamiedavenport** [comment]
@fakoredeDamilola how are you getting on with this?
